_version = 1.0

[brn-ex-iteration-1]

activity_id = "brn-ex-iteration-1"

[team]

members = [

    "limahswgc025@student.wethinkcode.co.za",

    "mamokswgc025@student.wethinkcode.co.za",

    "momolswgc025@student.wethinkcode.co.za",

    "nhmiyswgc025@student.wethinkcode.co.za",

    "thndwswgc025@student.wethinkcode.co.za"

]